#!/bin/bash

START_DIR="$PWD"

set -e -u -o pipefail

main() {
    exit_on_invalid_commit_msg "$1"
}

exit_on_invalid_commit_msg() {
    cd ./scripts
    cat "../$1" |
        grep -v -e '^#' |
            yarn run lint:commit
    cd "$START_DIR"
}

main "$1"
