#!/bin/bash

set -e -u -o pipefail

main() {
    if has_src_changed; then
        exit_on_lint_error
    fi
}

exit_on_lint_error() {
    for file in $(git diff --cached --name-only | grep -E '.rs$'); do
        rustfmt "$file"
        ./scripts/check-license-header.sh "$file"
    done
    cargo clippy
}

has_src_changed() {
    git diff --cached --name-only | \
        grep -q -E "(crates/)"
}

main
