[package]
name = "os-adapter"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Adapter for OSes supported by vulner"
license.workspace = true
keywords = ["os", "adapter"]

[dependencies]
package-model.workspace = true

log.workspace = true
