[workspace]
members = [
    "crates/cli",
    "crates/cpe-tag",
    "crates/os-adapter",
    "crates/package-model",
    "crates/security-advisories",
]

[profile.release]
strip = "symbols"
opt-level = "z"
lto = true
codegen-units = 1
