[package]
name = "package-model"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Package model"
license.workspace = true
keywords = ["package", "model"]

[dependencies]
lazy_static.workspace = true
regex.workspace = true
serde.workspace = true
