[package]
name = "cpe-tag"
version = "0.1.0"
authors = ["mrl5"]
edition = "2021"
description = "Generates valid NVD CPEs"
license = "MPL-2.0"
keywords = ["cpe", "nvd", "linux"]

[dependencies]
pyo3 = { version = "0.15.1", features = ["auto-initialize"] }
log = "0.4.14"
