[package]
name = "cpe-tag"
version = "0.1.1"
authors = ["mrl5"]
edition = "2021"
description = "Generates valid NVD CPEs"
license = "MPL-2.0"
keywords = ["cpe", "nvd", "linux"]

[package.metadata.workspaces]
independent = true

[dependencies]
pyo3 = { version = "0.15.1", features = ["auto-initialize"] }
log = "0.4.14"
grep = "0.2.8"
jsonschema = "0.14.0"
serde_json = "1.0.78"
serde = "1.0.136"
pythonize = "0.15.0"
regex = "1.5.4"
