# https://github.com/actions/create-release
# https://github.com/actions/upload-release-asset
name: draft-release

on:
  push:
    tags:
      - 'v*'
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Create TAR.GZ artifact
        run: |
          mkdir -p artifacts
          tar czhvf \
            artifacts/full-source.tar.gz \
            --exclude="*metarepo-cpe-tag*" \
            crates/ Cargo.* Makefile scripts/ README.md LICENSE

      - name: Create ZIP artifact
        run: |
          mkdir -p artifacts
          zip --exclude "*metarepo-cpe-tag*" \
            --recurse-paths \
            artifacts/full-source.zip \
            crates/ Cargo.* Makefile scripts/ README.md LICENSE

      - name: Build from TAR.GZ artifact
        run: |
          mkdir -p build
          tar xzvf artifacts/full-source.tar.gz --directory=build
          cd build/
          make build

      - name: Create draft release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            DRAFT
          draft: true
          prerelease: true

      - name: Upload TAR.GZ release asset
        id: upload-tar-gz-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/full-source.tar.gz
          asset_name: full-source.tar.gz
          asset_content_type: application/gzip

      - name: Upload ZIP release asset
        id: upload-zip-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/full-source.zip
          asset_name: full-source.zip
          asset_content_type: application/zip
