name: linter

on:
  push:
    branches: [ master ]
    paths:
      - '**.rs'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Lint
      run: make lint-ci
