name: tests

on:
  push:
    branches: [ master ]
    paths:
      - '**.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '**/Cargo.toml'
      - '**/Cargo.lock'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions-rs/toolchain@v1
      with:
        profile: default
        toolchain: stable

    - uses: Swatinem/rust-cache@v1

    - name: Run tests
      run: make test
