name: master

on:
  push:
    branches: [ master ]
    paths:
      - '**.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  pull_request:
    branches: [ master ]
    paths:
      - '**.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '**/Cargo.toml'
      - '**/Cargo.lock'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Lint
      run: make lint-ci

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: make test
